workspace:
  base: /app
  path: .

pipeline:
  build-2.7.14:
    image: python:2.7.14
    secrets: [github_auth_token]
    commands:
      - pip install --upgrade pip setuptools wheel
      - pip install flake8
      - pip install -e .
      - ls -lah
      - pwd
      - git fetch --tags
      - git status
      - git tag -l
      - python setup.py --version
      - flake8
      - pytest examples/
  build-3.7.1:
    image: python:3.7.1
    secrets: [github_auth_token]
    commands:
      - pip install --upgrade pip setuptools wheel
      - pip install -e .
      - pytest examples/
  pypi-publish:
    image: python:2.7.14
    secrets: [github_auth_token, username, password]
    commands:
#      - apt-get install git
#      - git config --global "url.https://$${GITHUB_AUTH_TOKEN}@github.com.insteadOf" ssh://git@github.com
      - pip install --upgrade pip setuptools wheel twine
      - python setup.py --version
      - python setup.py sdist
      - twine upload dist/pytest-yield-${DRONE_TAG}.zip -u $USERNAME -p $PASSWORD
    when:
      event: tag