pipeline:
  build-2.7.14:
    image: python:2.7.14-alpine
    commands:
      - pip install --upgrade pip setuptools wheel
      - pip install flake8
      - pip install -e .
      - flake8
      - pytest examples/
  build-3.7.1:
    image: python:3.7.1-alpine
    commands:
      - pip install --upgrade pip setuptools wheel
      - pip install -e .
      - pytest examples/
  pypi_publish:
    image: gjtempleton/drone-pypi
    secrets: [username, password]
    when:
      event: tag
      status: success