pipeline:
  build-2.7.14:
    image: python:2.7.14
    secrets: [github_auth_token]
    commands:
      - apt-get install git
      - git config --global "url.https://$${GITHUB_AUTH_TOKEN}@github.com.insteadOf" ssh://git@github.com
      - pip install --upgrade pip setuptools wheel
      - pip install flake8
      - pip install -e .
      - flake8
      - pytest examples/
  build-3.7.1:
    image: python:3.7.1
    secrets: [github_auth_token]
    commands:
      - apt-get install git
      - git config --global "url.https://$${GITHUB_AUTH_TOKEN}@github.com.insteadOf" ssh://git@github.com
      - pip install --upgrade pip setuptools wheel
      - pip install -e .
      - pytest examples/
  pypi_publish:
    image: gjtempleton/drone-pypi
    secrets: [username, password]
    username: $USERNAME
    password: $PASSWORD
    when:
      event: [tag]
      branch: [master]